name: Puid Dev

on:
  push:
    branches: [ dev ]

jobs:
  linux:
    name: Linux (Swift ${{ matrix.swift }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        swift: ['5.9', '5.10']
    container: swift:${{ matrix.swift }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build
        run: swift build -v
      - name: Test
        run: swift test -v

  macos:
    name: macOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build
        run: swift build -v
      - name: Test
        run: swift test -v

  lint_macos:
    name: Lint (macOS)
    runs-on: macos-latest
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install SwiftLint
        run: brew install swiftlint
      - name: SwiftLint
        run: swiftlint --strict
      - name: Install swift-format
        run: brew install swift-format
      - name: swift-format lint
        run: swift-format lint --configuration .swift-format --recursive Sources Tests
