name: Puid Dev

on:
  push:
    branches: [ dev ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, ubuntu-latest ]
swift: [ '5.9', '5.10' ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: SwiftLint (macOS)
        if: runner.os == 'macOS'
        uses: norio-nomura/action-swiftlint@v3.6.1
        with:
          args: --strict

      - name: Install swift-format (macOS)
        if: runner.os == 'macOS'
        run: brew install swift-format

      - name: swift-format lint (macOS)
        if: runner.os == 'macOS'
        run: swift-format --configuration .swift-format --mode lint --recursive Sources Tests

      - name: Setup Swift (Linux)
        if: runner.os == 'Linux'
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: ${{ matrix.swift }}

      - name: Build
        run: swift build -v

      - name: Test
        run: swift test -v
