name: Puid Tests

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, ubuntu-latest ]
swift: [ '5.9', '5.10' ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: SwiftLint (macOS)
        if: runner.os == 'macOS'
        uses: norio-nomura/action-swiftlint@v3.6.1
        with:
          args: --strict

      - name: Install swift-format (macOS)
        if: runner.os == 'macOS'
        run: brew install swift-format

      - name: swift-format lint (macOS)
        if: runner.os == 'macOS'
        run: swift-format --configuration .swift-format --mode lint --recursive Sources Tests

      - name: Setup Swift (Linux)
        if: runner.os == 'Linux'
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: ${{ matrix.swift }}

      - name: Build
        run: swift build -v

      - name: Checkout Data Submodule
        run: git submodule update --init --recursive

      - name: Run Tests (Linux)
        if: runner.os == 'Linux'
        run: swift test -v

      - name: Run Tests with Coverage (macOS)
        if: runner.os == 'macOS'
        run: swift test --enable-code-coverage -v

      - name: Generate Coverage Report (macOS)
        if: runner.os == 'macOS'
        run: xcrun llvm-cov export -format="lcov" .build/debug/PuidPackageTests.xctest/Contents/MacOS/PuidPackageTests -instr-profile .build/debug/codecov/default.profdata > coverage_report.lcov

      - name: Upload Coverage Report (macOS)
        if: runner.os == 'macOS'
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          files: ./coverage_report.lcov
          verbose: true
